import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import  Providers  from "./providers";
import { Toaster } from "react-hot-toast";
const geistSans = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        href="https://cdn.jsdelivr.net/npm/remixicon@4.5.0/fonts/remixicon.css"
        rel="stylesheet"
        precedence="default"
      />
      <body
        cz-shortcut-listen="true"
        className={`${geistSans.variable} antialiased bg-[#D3E7F0] `}
      >
       <Providers>{children}</Providers>
       <Toaster
        position="top-right"
        reverseOrder={false}
        toastOptions={{
          className: "bg-[#034F75] text-white font-semibold",
          style: {
            background: "#034F75",
            color: "#ffffff",
            fontSize: "14px",
          },
          success: {
            duration: 3000,
            theme: {
              primary: "#4ade80", // Green
              secondary: "#f0f9ff", // Light Blue
            },
          },
        }}
      />
      </body>
    </html>
  );
}
