import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import  Providers  from "./providers";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        href="https://cdn.jsdelivr.net/npm/remixicon@4.5.0/fonts/remixicon.css"
        rel="stylesheet"
        precedence="default"
      />
      <body
        cz-shortcut-listen="true"
        className={`${geistSans.variable} antialiased bg-[#D3E7F0] `}
      >
       <Providers>{children}</Providers>
       <ToastContainer
  position="top-right"
  autoClose={3000}
  hideProgressBar={false}
  newestOnTop={false}
  closeOnClick
  rtl={false}
  pauseOnFocusLoss
  draggable
  pauseOnHover
  closeButton={false}
 
  
 
   
  
  theme="colored"
  toastClassName="!p-0 !bg-transparent !shadow-none !rounded-none"
 
/>
      </body>
    </html>
  );
}
