import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const geistSans = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        href="https://cdn.jsdelivr.net/npm/remixicon@4.5.0/fonts/remixicon.css"
        rel="stylesheet"
        precedence="default"
      />
      <body
        cz-shortcut-listen="true"
        className={`${geistSans.variable} antialiased bg-[#D3E7F0] `}
      >
       <Providers>{children}</Providers>
      </body>
    </html>
  );
}
